services:

    student-1-backend:
        build:
            context: ./student-1/backend
            dockerfile: Api/Dockerfile
        ports:
            - "5101:8080"
        volumes:
            - student-1-db:/app/Data
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

    student-3-backend:
        build:
            context: ./student-3/backend
            dockerfile: Api/Dockerfile
        ports:
            - "5103:8080"
        volumes:
            - student-3-db:/app/Data
        environment:
            ASPNETCORE_ENVIRONMENT: Development

    student-1-frontend:
        build:
            context: .
            dockerfile: student-1/frontend/Dockerfile

    ai-mode:
        build:
            context: ./ai-services/ai-mode
            dockerfile: Api/Dockerfile
        environment:
            OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

    shared-shell:
        build:
            context: .
            dockerfile: shared/frontend/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - student-1-frontend
            - student-1-backend

volumes:
    student-1-db:
    student-3-db:
