import { test, expect } from '@playwright/test'

test.describe('AI Chat Assistant & Past Sessions Drawer', () => {
  const mockSessions = [
    {
      id: '55555555-5555-5555-5555-555555555501',
      studentId: '11111111-1111-1111-1111-111111111111',
      title: 'Study Plan & Priority Chat',
      createdAtUtc: new Date().toISOString(),
      updatedAtUtc: new Date().toISOString(),
      messageCount: 2,
      lastMessage: 'Here is your prioritized study recommendation.',
    },
    {
      id: '55555555-5555-5555-5555-555555555502',
      studentId: '11111111-1111-1111-1111-111111111111',
      title: 'Course Policy Discussion',
      createdAtUtc: new Date(Date.now() - 86400000).toISOString(),
      updatedAtUtc: new Date(Date.now() - 86400000).toISOString(),
      messageCount: 1,
      lastMessage: 'Late submissions incur a 5% penalty.',
    },
  ]

  const mockDetail = {
    id: '55555555-5555-5555-5555-555555555501',
    studentId: '11111111-1111-1111-1111-111111111111',
    title: 'Study Plan & Priority Chat',
    createdAtUtc: new Date().toISOString(),
    updatedAtUtc: new Date().toISOString(),
    messages: [
      {
        id: 'msg-1',
        chatSessionId: '55555555-5555-5555-5555-555555555501',
        role: 'assistant',
        content: '### ⚡ Notification Summary\n\nYou have 2 approaching deadlines and 1 unread grade.\n\n*How can I help you today?*',
        createdAtUtc: new Date(Date.now() - 600000).toISOString(),
        confidence: 'HIGH',
      },
    ],
  }

  test.beforeEach(async ({ page }) => {
    await page.route('**/api/chat/sessions**', async (route) => {
      const request = route.request()
      const url = new URL(request.url())
      const pathname = url.pathname

      if (request.method() === 'GET' && pathname === '/api/chat/sessions') {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(mockSessions),
        })
      } else if (request.method() === 'GET' && pathname.includes('55555555-5555-5555-5555-555555555501')) {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(mockDetail),
        })
      } else if (request.method() === 'POST' && pathname.endsWith('/messages')) {
        const payload = JSON.parse(request.postData() || '{}')
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            id: 'msg-reply',
            chatSessionId: '55555555-5555-5555-5555-555555555501',
            role: 'assistant',
            content: `Here is your customized study guidance for: **${payload.content}**.\n\n- Task 1: Complete 41026 Sprint\n- Task 2: Review Quiz feedback`,
            createdAtUtc: new Date().toISOString(),
            confidence: 'HIGH',
            citationsJson: JSON.stringify(['course_policies.md']),
          }),
        })
      } else if (request.method() === 'POST' && pathname.endsWith('/initial-digest')) {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            id: 'msg-digest',
            chatSessionId: '55555555-5555-5555-5555-555555555501',
            role: 'assistant',
            content: '### ⚡ Notification Summary\n\nBrand new digest freshly generated by AI assistant.',
            createdAtUtc: new Date().toISOString(),
            confidence: 'HIGH',
          }),
        })
      } else if (request.method() === 'POST' && pathname === '/api/chat/sessions') {
        // create session
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({
            id: '55555555-5555-5555-5555-555555555503',
            studentId: '11111111-1111-1111-1111-111111111111',
            title: 'New Chat Session',
            createdAtUtc: new Date().toISOString(),
            updatedAtUtc: new Date().toISOString(),
            messageCount: 0,
            lastMessage: null,
          }),
        })
      } else {
        await route.continue()
      }
    })

    await page.goto('./digest')
  })

  test('renders chat header and toggleable past chats drawer', async ({ page }) => {
    const toggleBtn = page.getByRole('button', { name: /PAST CHATS/ })
    await expect(toggleBtn).toBeVisible()

    // Open drawer
    await toggleBtn.click()
    await expect(page.locator('.nb-drawer')).toHaveClass(/nb-drawer--open/)
    await expect(page.locator('.nb-drawer__title')).toHaveText('PAST CHATS')
    await expect(page.locator('.nb-drawer__item')).toHaveCount(2)

    // Close drawer
    await page.locator('.nb-drawer__close-btn').click()
    await expect(page.locator('.nb-drawer')).not.toHaveClass(/nb-drawer--open/)
  })

  test('displays opening notification summary in chat', async ({ page }) => {
    await expect(page.locator('.nb-message-bubble--assistant')).toBeVisible()
    await expect(page.locator('.nb-message-bubble--assistant')).toContainText('Notification Summary')
  })

  test('interacts with the AI chat assistant sending a message', async ({ page }) => {
    const input = page.locator('.nb-composer-input')
    await input.fill('What should I focus on first today?')
    await page.locator('.nb-btn--send').click()

    // Verify user bubble and assistant reply
    await expect(page.locator('.nb-message-content--user')).toContainText('What should I focus on first today?')
    await expect(page.locator('.nb-message-bubble--assistant').last()).toContainText('Here is your customized study guidance')
    await expect(page.locator('.nb-confidence-badge').last()).toBeVisible()
  })

  test('clicks quick chip prompt to send query', async ({ page }) => {
    const chip = page.getByRole('button', { name: 'What should I prioritize next?' })
    await expect(chip).toBeVisible()
    await chip.click()

    await expect(page.locator('.nb-message-content--user')).toContainText('What should I prioritize next?')
    await expect(page.locator('.nb-message-bubble--assistant').last()).toContainText('Here is your customized study guidance')
  })
})
