import { test, expect } from '@playwright/test'

test.describe('AI Digest & Assistant View', () => {
  const mockDigests = [
    {
      id: '55555555-5555-5555-5555-555555555501',
      studentId: '11111111-1111-1111-1111-111111111111',
      summary: 'Good morning! You have 2 assignments due this week and 1 recent grade posted.',
      generatedAtUtc: new Date().toISOString(),
    },
    {
      id: '55555555-5555-5555-5555-555555555502',
      studentId: '11111111-1111-1111-1111-111111111111',
      summary: 'Yesterday summary: No critical alerts pending.',
      generatedAtUtc: new Date(Date.now() - 86400000).toISOString(),
    },
  ]

  test.beforeEach(async ({ page }) => {
    await page.route(/^http:\/\/localhost:5101\/notifications/, async (route) => {
      if (!route.request().url().includes('/stream')) {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify([]),
        })
      } else {
        await route.fulfill({
          status: 200,
          contentType: 'text/event-stream',
          body: 'event: connected\ndata: {}\n\n',
        })
      }
    })

    await page.route(/^http:\/\/localhost:5101\/digest/, async (route) => {
      const request = route.request()
      if (request.method() === 'GET') {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(mockDigests),
        })
      } else if (request.method() === 'POST' && request.url().includes('/generate')) {
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({
            id: '55555555-5555-5555-5555-555555555503',
            studentId: '11111111-1111-1111-1111-111111111111',
            summary: 'Brand new digest freshly generated by AI assistant.',
            generatedAtUtc: new Date().toISOString(),
          }),
        })
      } else if (request.method() === 'POST' && request.url().includes('/chat')) {
        const payload = JSON.parse(request.postData() || '{}')
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            reply: `Here is your customized study recommendation for: **${payload.prompt}**.\n\n- Task 1: Complete 41026 Sprint\n- Task 2: Review Quiz feedback`,
            repliedAtUtc: new Date().toISOString(),
          }),
        })
      } else {
        await route.continue()
      }
    })

    await page.goto('./digest')
  })

  test('renders latest digest card and past history', async ({ page }) => {
    await expect(page.locator('.nb-digest__title')).toHaveText('AI DIGEST')
    await expect(page.locator('.nb-digest-card')).toBeVisible()
    await expect(page.locator('.nb-digest-card')).toContainText('Good morning! You have 2 assignments due')

    // Past history
    await expect(page.locator('.nb-history')).toBeVisible()
    await expect(page.locator('.nb-history__row')).toHaveCount(2)
  })

  test('generates a new AI digest on button click', async ({ page }) => {
    const generateBtn = page.getByRole('button', { name: 'GENERATE DIGEST', exact: true })
    await expect(generateBtn).toBeVisible()
    await generateBtn.click()

    await expect(page.locator('.nb-digest-card')).toContainText('Brand new digest freshly generated')
  })

  test('interacts with the AI chat assistant', async ({ page }) => {
    await expect(page.locator('.nb-chat-panel')).toBeVisible()
    await expect(page.locator('.nb-chat-panel__title')).toHaveText('INTERACTIVE DIGEST ASSISTANT')

    // Type a prompt and send
    const input = page.locator('.nb-chat-panel__input')
    await input.fill('What should I focus on first today?')
    await page.locator('.nb-chat-panel__submit').click()

    // Verify user bubble and assistant bubble
    await expect(page.locator('.nb-chat-msg--user')).toContainText('What should I focus on first today?')
    await expect(page.locator('.nb-chat-msg--assistant').last()).toContainText('Here is your customized study recommendation')
  })

  test('clicks quick chip prompt to start conversation', async ({ page }) => {
    const chip = page.getByRole('button', { name: 'What should I prioritize in the next 2 hours?' })
    await expect(chip).toBeVisible()
    await chip.click()

    await expect(page.locator('.nb-chat-msg--user')).toContainText('What should I prioritize in the next 2 hours?')
    await expect(page.locator('.nb-chat-msg--assistant').last()).toContainText('Here is your customized study recommendation')
  })
})
