using System.Net;
using System.Net.Http.Json;
using Api.Data;
using Api.DTOs;
using Api.Models;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using Xunit;

namespace Api.Tests.Integration;

public sealed class AiDigestEndpointsTests : IClassFixture<CustomWebApplicationFactory>
{
    private readonly CustomWebApplicationFactory _factory;
    private readonly HttpClient _client;

    public AiDigestEndpointsTests(CustomWebApplicationFactory factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task GenerateDigest_CallsServiceAndSavesDigest()
    {
        // Arrange
        await _factory.ResetDatabaseAsync();
        var studentId = Guid.NewGuid();

        _factory.AiDigestServiceMock
            .Setup(s => s.GenerateDigestAsync(studentId, It.IsAny<IReadOnlyList<Notification>>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Here is your daily summary generated by AI.");

        // Act
        var response = await _client.PostAsync($"/digest/generate?studentId={studentId}", null);

        // Assert
        Assert.Equal(HttpStatusCode.Created, response.StatusCode);
        var digest = await response.Content.ReadFromJsonAsync<AiDigestDto>();
        Assert.NotNull(digest);
        Assert.Equal(studentId, digest.StudentId);
        Assert.Equal("Here is your daily summary generated by AI.", digest.Summary);
    }

    [Fact]
    public async Task GetDigests_ReturnsListOfDigestsForStudent()
    {
        // Arrange
        await _factory.ResetDatabaseAsync();
        var studentId = Guid.NewGuid();

        using (var scope = _factory.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
            db.AiDigests.AddRange(
                new AiDigest
                {
                    StudentId = studentId,
                    Summary = "Digest 1",
                    GeneratedAtUtc = DateTime.UtcNow.AddDays(-1)
                },
                new AiDigest
                {
                    StudentId = studentId,
                    Summary = "Digest 2",
                    GeneratedAtUtc = DateTime.UtcNow
                }
            );
            await db.SaveChangesAsync();
        }

        // Act
        var response = await _client.GetAsync($"/digest?studentId={studentId}");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var list = await response.Content.ReadFromJsonAsync<List<AiDigestDto>>();
        Assert.NotNull(list);
        Assert.Equal(2, list.Count);
        Assert.Equal("Digest 2", list[0].Summary); // Ordered by descending
    }

    [Fact]
    public async Task AskAssistant_EmptyPrompt_ReturnsBadRequest()
    {
        // Arrange
        var request = new AskAssistantRequestDto(Guid.NewGuid(), "", null);

        // Act
        var response = await _client.PostAsJsonAsync("/digest/chat", request);

        // Assert
        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
    }

    [Fact]
    public async Task AskAssistant_ValidPrompt_ReturnsReply()
    {
        // Arrange
        var studentId = Guid.NewGuid();
        var request = new AskAssistantRequestDto(
            StudentId: studentId,
            Prompt: "What is my next priority?",
            History: [new ChatMessageDto("user", "Hello")]
        );

        _factory.AiDigestServiceMock
            .Setup(s => s.AskAssistantAsync(
                studentId,
                "What is my next priority?",
                It.IsAny<IReadOnlyList<ChatMessageDto>>(),
                It.IsAny<IReadOnlyList<Notification>>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync("Your next priority is Sprint 1 submission.");

        // Act
        var response = await _client.PostAsJsonAsync("/digest/chat", request);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var result = await response.Content.ReadFromJsonAsync<AskAssistantResponseDto>();
        Assert.NotNull(result);
        Assert.Equal("Your next priority is Sprint 1 submission.", result.Reply);
    }
}
