// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902093105_AddAssignmentExtensionSubject")]
    partial class AddAssignmentExtensionSubject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Api.Models.Automation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Deleted");

                    b.ToTable("Automations", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.AutomationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AutomationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutionTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomationId", "ExecutionTimeStamp");

                    b.ToTable("AutomationRuns", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.AssignmentExtensionAutomation", b =>
                {
                    b.HasBaseType("Api.Models.Automation");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FurtherDetails")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssignmentExtensionAutomations", (string)null);
                });

            modelBuilder.Entity("Api.Models.ScheduledPostAutomation", b =>
                {
                    b.HasBaseType("Api.Models.Automation");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GroupConversation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable("ScheduledPostAutomations", (string)null);
                });

            modelBuilder.Entity("Api.Models.AssignmentExtensionAutomationRun", b =>
                {
                    b.HasBaseType("Api.Models.AutomationRun");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("AssignmentExtensionAutomationRuns", (string)null);
                });

            modelBuilder.Entity("Api.Models.ScheduledPostAutomationRun", b =>
                {
                    b.HasBaseType("Api.Models.AutomationRun");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GroupConversation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable("ScheduledPostAutomationRuns", (string)null);
                });

            modelBuilder.Entity("Api.Models.AutomationRun", b =>
                {
                    b.HasOne("Api.Models.Automation", "Automation")
                        .WithMany("Runs")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automation");
                });

            modelBuilder.Entity("Api.Models.AssignmentExtensionAutomation", b =>
                {
                    b.HasOne("Api.Models.Automation", null)
                        .WithOne()
                        .HasForeignKey("Api.Models.AssignmentExtensionAutomation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.ScheduledPostAutomation", b =>
                {
                    b.HasOne("Api.Models.Automation", null)
                        .WithOne()
                        .HasForeignKey("Api.Models.ScheduledPostAutomation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.AssignmentExtensionAutomationRun", b =>
                {
                    b.HasOne("Api.Models.AutomationRun", null)
                        .WithOne()
                        .HasForeignKey("Api.Models.AssignmentExtensionAutomationRun", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.ScheduledPostAutomationRun", b =>
                {
                    b.HasOne("Api.Models.AutomationRun", null)
                        .WithOne()
                        .HasForeignKey("Api.Models.ScheduledPostAutomationRun", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Automation", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
